spring.application.name=AUTH-SERVICE

server.port=8082

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

jwt.secret=ThisIsMyVerySecretKeyForHotelManagementProject
jwt.expiration=86400000

springdoc.swagger-ui.path=/swagger-ui.html